name: Fly Deploy
on:
  push:
    paths:
      - 'sekun/**'
      - '.github/workflows/**'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy-sekun:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sekun
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Deploy with flyctl
        uses: superfly/flyctl-actions@1.3
        with:
          args: "deploy"
